server:
  port: 8080
feign:
  hystrix:
    enabled: true
spring:
  application:
    name: user-consumer # 应用名称
eureka:
  client:
    service-url: # EurekaServer地址
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    prefer-ip-address: true # 当调用getHostname获取实例的hostname时，返回ip而不是host名称
    ip-address: 127.0.0.1 # 指定自己的ip信息，不指定的话会自己寻找
logging:
  level:
    com.example.consumer: debug


data:
  env: test
  user:
    username: username11
    password: password11